//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AZReport.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.IO;
    using System.Linq;

    public partial class AZModelContainer : DbContext
    {
        public AZModelContainer()
            : base("name=AZModelContainer")
        {
            AppDomain.CurrentDomain.SetData("DataDirectory", Path.Combine(AppDomain.CurrentDomain.BaseDirectory, ""));
            //disable initializer
            //Database.SetInitializer<AZModelContainer>(null);
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
        }

        public DbSet<Level> Levels { get; set; }
        public DbSet<Program> Programs { get; set; }
        public DbSet<Sale> Sales { get; set; }
        public DbSet<Schedule> Schedules { get; set; }
        public DbSet<TimeSetting> TimeSettings { get; set; }
      
    }
}
